### PR TITLE
Cleanup + NuGet package generation target and script added

### PR DESCRIPTION
**Pull request by falahati**
After this commit, it is possible to generate the nuget package using the build script. You can also use the publish script to publish the packages. Please note that there are two packages, one with xml and pdb files and other without. nuget automatically figure out how to upload them. Also instead of editing the nuspec file for versioning, you only need to update the 'ISocketLite.PCL' project properties. nuget automatically update the nuspec file. This is also good because different dll(s) versions are no longer interchangeable and makes the debugging much easier.
However, all other projects are still on version 1.0.0 so bait and switch pattern is still in place.
I also made some small cleanups and moved the SocketLite.PCL project to a new directory. I hope that you accept the changes.

Thanks

### CODE REVIEW

**Review by 1iveowl — COMMENTED** [review]
Why did you add `new` here?

`protected new void InitializeUdpSocket()`

I'm not saying it's not right, I just don't understand it.

**Comment by 1iveowl** [comment]
Thanks. It's late but I'll have a closer look at it tomorrow.

**Comment by falahati** [comment]
To make it explicit that this method hides the parent method. Add it or not, compiler will add it for you. I just made it explicit.

> When used as a declaration modifier, the new keyword explicitly hides a member that is inherited from a base class. When you hide an inherited member, the derived version of the member replaces the base class version. **Although you can hide members without using the new modifier, you get a compiler warning. If you use new to explicitly hide a member, it suppresses this warning.**

**Comment by falahati** [comment]
I found the bug about the WindowsPhone 8.1 problem. Last commit fixes the problem

**Review by 1iveowl — APPROVED** [review]
Well spottet

**Review by 1iveowl — APPROVED** [review]

**Review by 1iveowl — APPROVED** [review]

**Review by 1iveowl — CHANGES_REQUESTED** [review]
We should just comment out InitializeUdpSocket() since it's already inherited from UdpSendBase. I'll make that change later.

**Review by 1iveowl — APPROVED** [review]

**Review by 1iveowl — APPROVED** [review]

**Review by 1iveowl — APPROVED** [review]

**Review by 1iveowl — APPROVED** [review]

**Pull request merged**
